# Site settings
title: Oji Ofong
description: 'Just another dev from somewhere on earth'
url: 'https://ojiofong.github.io'
baseurl: '/'
google_analytics: 'UA-00000-1-change-this'
disqus_shortname: 'ojiofong-github-io'

author:
  name: 'Oji Ofong'
  email: ojiofong@gmail.com
  github_username:  ojiofong
  linkedin_username:  oji-ofong-780ba0b0
#  twitter_username: ojiofong
#  facebook_username: ojiofong

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: pretty
markdown: kramdown
highlighter: rouge

  # do not cache in development - remove in production
sass:
  cache: false

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-gist', 'jemoji', 'jekyll-email-protect']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
